<template><div><h2 id="元数据" tabindex="-1"><a class="header-anchor" href="#元数据"><span>元数据</span></a></h2>
<ul>
<li>分类：深度学习</li>
<li>标签：显存分析, 优化器状态, 模型参数, 混合精度</li>
<li>日期：2025年4月12日</li>
</ul>
<h2 id="核心观点总结" tabindex="-1"><a class="header-anchor" href="#核心观点总结"><span>核心观点总结</span></a></h2>
<p>本文探讨了深度学习训练阶段的显存消耗，重点分析了模型参数、优化器状态、梯度值和激活值对显存的影响。通过计算公式，我们可以估算不同数据类型和优化器配置下的显存需求。</p>
<h2 id="重点段落" tabindex="-1"><a class="header-anchor" href="#重点段落"><span>重点段落</span></a></h2>
<h3 id="静态值分析" tabindex="-1"><a class="header-anchor" href="#静态值分析"><span>静态值分析</span></a></h3>
<ul>
<li>
<p><strong>模型显存</strong>：模型的显存消耗与参数量和数据类型有关。常见的数据类型有fp32、fp16/bf16和int8等。显存计算公式为：</p>
<p v-pre class='katex-block'><span class="katex-display"><span class="katex"><span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML" display="block"><semantics><mrow><mtext>ModelMem</mtext><mo>=</mo><mtext>TypeSize</mtext><mo>×</mo><mtext>Params</mtext></mrow><annotation encoding="application/x-tex">\text{ModelMem} = \text{TypeSize} \times \text{Params}
</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:0.6944em;"></span><span class="mord text"><span class="mord">ModelMem</span></span><span class="mspace" style="margin-right:0.2778em;"></span><span class="mrel">=</span><span class="mspace" style="margin-right:0.2778em;"></span></span><span class="base"><span class="strut" style="height:0.8778em;vertical-align:-0.1944em;"></span><span class="mord text"><span class="mord">TypeSize</span></span><span class="mspace" style="margin-right:0.2222em;"></span><span class="mbin">×</span><span class="mspace" style="margin-right:0.2222em;"></span></span><span class="base"><span class="strut" style="height:0.6833em;"></span><span class="mord text"><span class="mord">Params</span></span></span></span></span></span></p>
<p>根据不同数据类型，计算公式如下（单位：GB）：</p>
<ul>
<li><span v-pre class="katex"><span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mtext>fp32</mtext><mo>=</mo><mfrac><mrow><mn>4</mn><mo>×</mo><mtext>params</mtext></mrow><mrow><mn>1024</mn><mo>×</mo><mn>1024</mn><mo>×</mo><mn>1024</mn></mrow></mfrac></mrow><annotation encoding="application/x-tex">\text{fp32} = \frac{4 \times \text{params}}{1024 \times 1024 \times 1024}</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:0.8889em;vertical-align:-0.1944em;"></span><span class="mord text"><span class="mord">fp32</span></span><span class="mspace" style="margin-right:0.2778em;"></span><span class="mrel">=</span><span class="mspace" style="margin-right:0.2778em;"></span></span><span class="base"><span class="strut" style="height:1.3005em;vertical-align:-0.4033em;"></span><span class="mord"><span class="mopen nulldelimiter"></span><span class="mfrac"><span class="vlist-t vlist-t2"><span class="vlist-r"><span class="vlist" style="height:0.8972em;"><span style="top:-2.655em;"><span class="pstrut" style="height:3em;"></span><span class="sizing reset-size6 size3 mtight"><span class="mord mtight"><span class="mord mtight">1024</span><span class="mbin mtight">×</span><span class="mord mtight">1024</span><span class="mbin mtight">×</span><span class="mord mtight">1024</span></span></span></span><span style="top:-3.23em;"><span class="pstrut" style="height:3em;"></span><span class="frac-line" style="border-bottom-width:0.04em;"></span></span><span style="top:-3.4461em;"><span class="pstrut" style="height:3em;"></span><span class="sizing reset-size6 size3 mtight"><span class="mord mtight"><span class="mord mtight">4</span><span class="mbin mtight">×</span><span class="mord text mtight"><span class="mord mtight">params</span></span></span></span></span></span><span class="vlist-s">​</span></span><span class="vlist-r"><span class="vlist" style="height:0.4033em;"><span></span></span></span></span></span><span class="mclose nulldelimiter"></span></span></span></span></span></li>
<li><span v-pre class="katex"><span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mtext>fp16/bf16</mtext><mo>=</mo><mfrac><mrow><mn>2</mn><mo>×</mo><mtext>params</mtext></mrow><mrow><mn>1024</mn><mo>×</mo><mn>1024</mn><mo>×</mo><mn>1024</mn></mrow></mfrac></mrow><annotation encoding="application/x-tex">\text{fp16/bf16} = \frac{2 \times \text{params}}{1024 \times 1024 \times 1024}</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:1em;vertical-align:-0.25em;"></span><span class="mord text"><span class="mord">fp16/bf16</span></span><span class="mspace" style="margin-right:0.2778em;"></span><span class="mrel">=</span><span class="mspace" style="margin-right:0.2778em;"></span></span><span class="base"><span class="strut" style="height:1.3005em;vertical-align:-0.4033em;"></span><span class="mord"><span class="mopen nulldelimiter"></span><span class="mfrac"><span class="vlist-t vlist-t2"><span class="vlist-r"><span class="vlist" style="height:0.8972em;"><span style="top:-2.655em;"><span class="pstrut" style="height:3em;"></span><span class="sizing reset-size6 size3 mtight"><span class="mord mtight"><span class="mord mtight">1024</span><span class="mbin mtight">×</span><span class="mord mtight">1024</span><span class="mbin mtight">×</span><span class="mord mtight">1024</span></span></span></span><span style="top:-3.23em;"><span class="pstrut" style="height:3em;"></span><span class="frac-line" style="border-bottom-width:0.04em;"></span></span><span style="top:-3.4461em;"><span class="pstrut" style="height:3em;"></span><span class="sizing reset-size6 size3 mtight"><span class="mord mtight"><span class="mord mtight">2</span><span class="mbin mtight">×</span><span class="mord text mtight"><span class="mord mtight">params</span></span></span></span></span></span><span class="vlist-s">​</span></span><span class="vlist-r"><span class="vlist" style="height:0.4033em;"><span></span></span></span></span></span><span class="mclose nulldelimiter"></span></span></span></span></span></li>
<li><span v-pre class="katex"><span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mtext>fp8/int8</mtext><mo>=</mo><mfrac><mrow><mn>1</mn><mo>×</mo><mtext>params</mtext></mrow><mrow><mn>1024</mn><mo>×</mo><mn>1024</mn><mo>×</mo><mn>1024</mn></mrow></mfrac></mrow><annotation encoding="application/x-tex">\text{fp8/int8} = \frac{1 \times \text{params}}{1024 \times 1024 \times 1024}</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:1em;vertical-align:-0.25em;"></span><span class="mord text"><span class="mord">fp8/int8</span></span><span class="mspace" style="margin-right:0.2778em;"></span><span class="mrel">=</span><span class="mspace" style="margin-right:0.2778em;"></span></span><span class="base"><span class="strut" style="height:1.3005em;vertical-align:-0.4033em;"></span><span class="mord"><span class="mopen nulldelimiter"></span><span class="mfrac"><span class="vlist-t vlist-t2"><span class="vlist-r"><span class="vlist" style="height:0.8972em;"><span style="top:-2.655em;"><span class="pstrut" style="height:3em;"></span><span class="sizing reset-size6 size3 mtight"><span class="mord mtight"><span class="mord mtight">1024</span><span class="mbin mtight">×</span><span class="mord mtight">1024</span><span class="mbin mtight">×</span><span class="mord mtight">1024</span></span></span></span><span style="top:-3.23em;"><span class="pstrut" style="height:3em;"></span><span class="frac-line" style="border-bottom-width:0.04em;"></span></span><span style="top:-3.4461em;"><span class="pstrut" style="height:3em;"></span><span class="sizing reset-size6 size3 mtight"><span class="mord mtight"><span class="mord mtight">1</span><span class="mbin mtight">×</span><span class="mord text mtight"><span class="mord mtight">params</span></span></span></span></span></span><span class="vlist-s">​</span></span><span class="vlist-r"><span class="vlist" style="height:0.4033em;"><span></span></span></span></span></span><span class="mclose nulldelimiter"></span></span></span></span></span></li>
</ul>
</li>
<li>
<p><strong>优化器状态</strong>：在LLM中常用的优化器是Adam，它需要为每个参数维护Momentum和Variance状态。在混合精度训练中，还需一份模型参数副本。Adam的优化器状态显存计算公式为：</p>
<p v-pre class='katex-block'><span class="katex-display"><span class="katex"><span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML" display="block"><semantics><mrow><mtext>OptMem</mtext><mo>=</mo><mfrac><mrow><mo stretchy="false">(</mo><mn>4</mn><mo>+</mo><mn>4</mn><mo>+</mo><mn>4</mn><mo stretchy="false">)</mo><mo>×</mo><mtext>Params</mtext></mrow><mrow><mn>1024</mn><mo>×</mo><mn>1024</mn><mo>×</mo><mn>1024</mn></mrow></mfrac></mrow><annotation encoding="application/x-tex">\text{OptMem} = \frac{(4 + 4 + 4) \times \text{Params}}{1024 \times 1024 \times 1024}
</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:0.8778em;vertical-align:-0.1944em;"></span><span class="mord text"><span class="mord">OptMem</span></span><span class="mspace" style="margin-right:0.2778em;"></span><span class="mrel">=</span><span class="mspace" style="margin-right:0.2778em;"></span></span><span class="base"><span class="strut" style="height:2.1963em;vertical-align:-0.7693em;"></span><span class="mord"><span class="mopen nulldelimiter"></span><span class="mfrac"><span class="vlist-t vlist-t2"><span class="vlist-r"><span class="vlist" style="height:1.427em;"><span style="top:-2.314em;"><span class="pstrut" style="height:3em;"></span><span class="mord"><span class="mord">1024</span><span class="mspace" style="margin-right:0.2222em;"></span><span class="mbin">×</span><span class="mspace" style="margin-right:0.2222em;"></span><span class="mord">1024</span><span class="mspace" style="margin-right:0.2222em;"></span><span class="mbin">×</span><span class="mspace" style="margin-right:0.2222em;"></span><span class="mord">1024</span></span></span><span style="top:-3.23em;"><span class="pstrut" style="height:3em;"></span><span class="frac-line" style="border-bottom-width:0.04em;"></span></span><span style="top:-3.677em;"><span class="pstrut" style="height:3em;"></span><span class="mord"><span class="mopen">(</span><span class="mord">4</span><span class="mspace" style="margin-right:0.2222em;"></span><span class="mbin">+</span><span class="mspace" style="margin-right:0.2222em;"></span><span class="mord">4</span><span class="mspace" style="margin-right:0.2222em;"></span><span class="mbin">+</span><span class="mspace" style="margin-right:0.2222em;"></span><span class="mord">4</span><span class="mclose">)</span><span class="mspace" style="margin-right:0.2222em;"></span><span class="mbin">×</span><span class="mspace" style="margin-right:0.2222em;"></span><span class="mord text"><span class="mord">Params</span></span></span></span></span><span class="vlist-s">​</span></span><span class="vlist-r"><span class="vlist" style="height:0.7693em;"><span></span></span></span></span></span><span class="mclose nulldelimiter"></span></span></span></span></span></span></p>
</li>
</ul>
<h3 id="动态值分析" tabindex="-1"><a class="header-anchor" href="#动态值分析"><span>动态值分析</span></a></h3>
<ul>
<li><strong>激活值</strong>：激活值大小与模型参数、重计算策略、并行策略等相关。根据Megtron论文提供的公式，可以估算激活值占用的显存大小。</li>
</ul>
<h2 id="操作步骤" tabindex="-1"><a class="header-anchor" href="#操作步骤"><span>操作步骤</span></a></h2>
<ol>
<li>✅ <strong>确定数据类型</strong>：选择合适的数据类型（如fp32、fp16）来计算模型参数的显存消耗。</li>
<li>⚠ <strong>计算优化器状态</strong>：根据选择的优化器（如Adam），计算其状态参数所需的显存。</li>
<li>❗ <strong>评估激活值</strong>：使用参考公式评估激活值对显存的影响。</li>
</ol>
<h2 id="常见错误" tabindex="-1"><a class="header-anchor" href="#常见错误"><span>常见错误</span></a></h2>
<blockquote>
<p>⚠ 在计算模型显存时，忽略了数据类型对结果的影响。确保选择正确的数据类型进行估算。</p>
</blockquote>
<h2 id="💡-启发点" tabindex="-1"><a class="header-anchor" href="#💡-启发点"><span>💡 启发点</span></a></h2>
<p>混合精度训练可以有效减少显存占用，但需要注意最终存储时仍需转为fp32。</p>
<h2 id="行动清单" tabindex="-1"><a class="header-anchor" href="#行动清单"><span>行动清单</span></a></h2>
<ul class="task-list-container">
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-0" disabled="disabled"><label class="task-list-item-label" for="task-item-0"> 检查并优化当前模型的显存使用情况。</label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-1" disabled="disabled"><label class="task-list-item-label" for="task-item-1"> 探索混合精度训练在实际项目中的应用。</label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-2" disabled="disabled"><label class="task-list-item-label" for="task-item-2"> 学习并应用其他优化器以降低显存需求。</label></li>
</ul>
<blockquote>
<p>原始出处：[选取内容]</p>
</blockquote>
</div></template>


